### ISSUE TITLE
Как создать фильтр по кастомному полю с датой?

### ISSUE THREAD

**Issue by Shmanov** [Krukov/amocrm_api#101]
my_filter1 = [filters.DateRangeFilter("last_date")(datetime.datetime(2023,4,1),datetime.datetime.today())]

по стандартным АМОвским полям отрабатывает,  а по кастомным не отфильтровывает.

**Comment by Krukov** [comment]
да амосрм такого не предоставляет что бы по кастомным полям фильтровать

**Comment by rypMaH** [comment]
![image](https://github.com/Krukov/amocrm_api/assets/47295343/e02eb758-be8d-47ba-a004-569c83c65da6)

А этот метод не за фильтрацию кастомных полей отвечает?
