### ISSUE TITLE
ou need to get the phone number from the transaction

### ISSUE THREAD

**Issue by Vladik288** [Krukov/amocrm_api#106]
![photo_2023-11-02_15-07-22](https://github.com/Krukov/amocrm_api/assets/55274156/d263dd6e-7ff8-4cc1-867d-868a14a75118)

You need to get the phone number from the transaction, in which you need to get the contact and phone number with email.

**Comment by Krukov** [comment]
Didn't get what the issue/problem is? Maybe you can write in Russian? 

Можно по русски ? ))

**Comment by Vladik288** [comment]
Конечно, привык что все англоязычные форумы)) Проблема в том, что не могу достать контакт и email  из этих полей, также эти данные есть в разделе контакт. 
![image](https://github.com/Krukov/amocrm_api/assets/55274156/f87ed419-71b1-4bd6-9dcd-ca642467d9ab)
Если не трудно, можем перейти в какой-то месенджер для удобного общения?)

**Comment by Krukov** [comment]
Не хочу тут светит свой месенджер )) 

вообщем это кастомные поля и на нах нужно создать маппинг 
Можно воспользоваться автогенерацией как описано тут https://github.com/Krukov/amocrm_api/tree/master#%D0%BA%D0%B0%D1%81%D1%82%D0%BE%D0%BC%D0%BD%D1%8B%D0%B5-%D0%BF%D0%BE%D0%BB%D1%8F 
или как там же описано сделать вручную 

 ```python
 class Contact(_Contact):
    phone = custom_field.ContactPhoneField("Другой")
    email = custom_field.ContactEmailField("Email раб.")


class Lead(_Lead):

    phone = custom_field.TextCustomField("Телефон")
    ....
 
 ```

**Comment by Vladik288** [comment]
Спасибо, помогло! А чтобы брокера поменять надо его id передать? Подскажите с этим моментом, или тоже кастом поле?

**Comment by Vladik288** [comment]
Спасибо большое, разобрался)

**Comment by Krukov** [comment]
Хорошо я тогда закрою  ишью - если что создавай новую )
