### ISSUE TITLE
Не работает апи по изменению чего либо...

### ISSUE THREAD

**Issue by Krukov** [Krukov/amocrm_api#12]

**Comment by N-litened** [comment]
Я написал сегодня ПХП-скрипт, надранный по кусочкам с их документации, и он (если я не сошёл с ума пока) тоже не обновлял.
Послал его разработчикам Amo в саппорт-тикете, вечером прихожу — скрипт теперь обновляет, *amocrm_api* всё еще не обновляет. Значит, как мне кажется, теперь сохранение принципиально возможно, просто что-то поменялось в самом механизме, и нужно чуть адаптировать *amocrm_api*.

Прикладываю сам работающий PHP-скрипт, вверху можно вписать креденшлы доступа.
[testamo.txt](https://github.com/Krukov/amocrm_api/files/303271/testamo.txt)

Покопаюсь еще сейчас в самом *amocrm_api*, может, найду что-нибудь.

**Comment by N-litened** [comment]
Разобрался. Суть в том, что единственный метод апи, который принимает параметр &type=json — это /private/api/auth.php. Все остальные либо игнорируют его, либо не работают, когда он задан. Я проверил — сохранение не работает, когда задан такой параметр в URL.

Как это поправил — все мои скрипты заработали.

Сейчас сделаю пулреквест.

**Comment by Krukov** [comment]
Конечно сама суть такого поведения со стороны amocrm полностью не ясна. Жуть. 
Спасибо, что разобрались с этим, а то я уж голову сломал.
