### ISSUE TITLE
BaseCompany.tasks always returns nothing

### ISSUE THREAD

**Issue by N-litened** [Krukov/amocrm_api#14]
I've found out that BaseCompany.tasks returns empty collection, even when there are tasks assigned.
I've also found a way to make it work after playing with AmoCRM developer console.

The original code:

```
class CompanyTask(_AbstractTaskModel):
    company = fields.ForeignField(BaseCompany, 'element_id')
    _element_type = fields._ConstantField('element_type',
                                         _BaseModel._ELEMENT_TYPES['company'])
    objects = TasksManager(object_type='contact')
```

If we remove _object_type_ (make it `objects = TasksManager()`) it works. Also the _object_type_ can be removed from ContactTask and LeadTask class without changing the way they work (they work either way).

I am not sure that's the right way to do it though for this wrapper, since maybe AmoCRM's behavior will change in the future again.

**Comment by Krukov** [comment]
Зарываю связи с давность и предстоящим рефаторингом https://github.com/Krukov/amocrm_api/issues/28
