### ISSUE TITLE
Не обрабатывается ошибка сохранения

### ISSUE THREAD

**Issue by lavr** [Krukov/amocrm_api#19]
Пытаемся сохранить изменения в сделке:

    lead.save()

Класс _BaseAmoManager делает post-запрос:

    https://xxx.amocrm.ru/private/api/v2/json/leads/set 

получает ответ (со статусом 200):

    {"response":{"leads":{"update":{"errors":{"17207117":"Last modified date is older than in database"}}},"server_time":1513160837}}

но считает, что всё прошло хорошо.

Ожидаемое поведение:  библиотека сообщает об ошибке при сохранении сделки.

**Comment by Krukov** [comment]
Спасибо, но я навряд ли уже буду поддержкой это либы. Написал в readme unmaintained
