### ISSUE TITLE
Удаляются контакты в полях EnumCustomField с множественным значениями

### ISSUE THREAD

**Issue by alex-msk** [Krukov/amocrm_api#24]
Дано: 
Контакт, у которого есть несколько "Рабочих" адресов и один "Личный". 
Нужно изменить первый из них. 

```python
class Contact(BaseContact):
	email=fields.EnumCustomField(u'Email', enum='WORK')
```

Получаем список контактов. 

```python
contact=Contact.objects.get(id=12345)
print(contact.email)
# ['email1@mail.com', 'email2@mail.com']
```

В массиве только "Рабочие" адреса. Пытаемся поменять первый рабочий адрес.  

```python
if isinstance(contact.email , list):
    tmp_mails=contact.email
    tmp_mails[0]='test@address.com'
    contact.email = tmp_mails
contact.save()
```

В результате,  все "Рабочие" контакты сохраняются корректно в CRM, а "Личные" просто удаляются. Подскажите, может неправильно пользуюсь библиотекой?

**Comment by Krukov** [comment]
Простите что так и не дождались ответа ) Я уже не поддерживаю эту библиотеку, и думаю что и апи у  АМОСрм уже сильно изменилось.

**Comment by alex-msk** [comment]
Жаль, что не поддерживаете.  Одна из самых удобных из имеющихся на данный момент. 
Изменения в API на самом деле совсем незначительные. 
У меня библиотека используется в "боевом" проекте. С небольшими правками, все работает нормально.

**Comment by Krukov** [comment]
Да я тоже использовал ее и не в одном проекте на бою, но само апи AMOCrm мне доставило не мало боли ))  Если нужно выпустить новую версию с вашим фиксом - скажите я зарелижу.

**Comment by alex-msk** [comment]
Ок, тогда чуть позже пересмотрю еще раз все, что написал с сделаю pull request.есть ощущение, что там много корявок наспех сделано )

**Comment by Krukov** [comment]
Закрываю связи с давностью и предстояшим рефакторингом https://github.com/Krukov/amocrm_api/issues/28
