### ISSUE TITLE
Поддержка OAuth2

### ISSUE THREAD

**Issue by alex-msk** [Krukov/amocrm_api#27]
В июле 2020 года, AmoCRM отказались от поддержки авторизации через api_key. Вместо api_key предполагается использовать авторизацию через OAuth2.

Подробности: https://www.amocrm.ru/developers/content/oauth/switch-over-oauth

**Comment by Krukov** [comment]
Интересно конечно, как они считают должна поисходить интеграция бекенда с этим чудом? Я вижу только один вариант - получение access и refresh  токена по упращенной авторизации , но как быть с тем что 
```
Refresh token имеет два существенных ограничения его жизни:

Refresh токен действует всего 3 месяца. Если интеграция не используется в течение 3 месяцев, не было ни одного запроса на актуализацию ключа, то интеграция потеряет доступ к данным и будем необходимо повторно запрашивать разрешение у пользователя на доступ к его аккаунту
Refresh token можно обменять только один раз. После отправки его в метод и получения новой пары access token/refresh token старый refresh token становится не актуальным. И после получения нового refresh token его необходимо обязательно сохранить, иначе придется вновь перезапрашивать доступ у пользователя.
```

**Comment by Krukov** [comment]
Придется иметь какойто апи для определения где хранятся токены ...
 Мне понадобилось реанимировать либу  )) , придется это заиплементить

**Comment by alex-msk** [comment]
Было бы хорошо, если либа реанимируется, как никак единственная более менее рабочая оболочка для Python ).
А что нибудь вроде [этого](https://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#backend-application-flow) может помочь?

**Comment by Krukov** [comment]
Проблема в том что Oauth многогранен (там есть 3 или 4 типа получения конечного токена), и в этой ссылке описан  "Client Credentials Grant Type " который скорей всего не поддерживается amocrm  (можно попробовать конечно) так как является самым не безопасным ) . Попробую ...

**Comment by Krukov** [comment]
Я глянул на их либу на php и там предполагается что пользователя (веб ) должен перейти на страничку и получить код отпавить его на бек .... - то есть я совсем не понимаю как они думают это можно использовать в случае интерации  с бекендом (

**Comment by alex-msk** [comment]
Не обязательно. Есть вариант попроще: создать в панели интеграцию от своего имени и сразу получить Secret, Client-id и код авторизации. 
Только эта интеграция будет действовать от имени того пользователя, от которого была создана.

Подробнее тут: https://www.amocrm.ru/developers/content/oauth/step-by-step#easy_auth

Можно пойти по этому варианту для более простого запуска.

**Comment by alex-msk** [comment]
Вот еще ссылка: https://www.amocrm.ru/developers/content/oauth/easy-auth

**Comment by Krukov** [comment]
Да я пошел по этому пути - но проьблемма остается : код авторизации которые можно забрать с интерации однаразовый + refresh токен одноразовый - получается что его гдето нужно хранить для того что бы приложение даже после перезапуска работало

**Comment by alex-msk** [comment]
Так у нас же вроде есть client_secret, который не должен меняться, есть ClientID, что подпадает под это описание: 

https://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#backend-application-flow <https://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#backend-application-flow>

И там же есть механизм по автоматическому рефрешу токенов: 

https://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#third-recommended-define-automatic-token-refresh-and-update <https://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#third-recommended-define-automatic-token-refresh-and-update>

или я что то путаю? 

А для хранения токенов кроме tmp что то ничего правильного в голову не приходит. т.к. не предполагается доступ ни к сессии ни к БД. 
Ну или заново все получать при рестарте.

**Comment by Krukov** [comment]
Этот backend application flow предполагает что Oauth провайдер (Amocrm) поддерживает grand_type client_credentials (https://github.com/oauthlib/oauthlib/blob/6875e3ac513a3828c3328d4f585d4c38b2b2c698/oauthlib/oauth2/rfc6749/clients/backend_application.py#L31)
 Я проверил (в доке негде не описано про это тоже) что они это не поддердивают

Насчет хранения refresh_token'ов  - библиотека может предосталять интерфейс для того что бы самому можно было определить где ты хочешь хранить токен (будь то база или redis или whatever)
```
class TokensStorage:

    def get_access_token(self) -> Optional[str]:
        pass

    def get_refresh_token(self) -> Optional[str]:
        pass

    def save_tokens(self, access_token: str, refresh_token: str):
        pass
```

Заново все получать - сомнительное удовостьвие , так как код авторизации однаразовый и придется его каждый раз генерить перед перезапуском прилождения и прокидывать его  при старте, что кажется просто убиственным если у когото веб приложение которое еще и  какомнибудь докер оркестраторе ранится

**Comment by Krukov** [comment]
переходит в https://github.com/Krukov/amocrm_api/issues/28
