### ISSUE TITLE
Новая версия 

### ISSUE THREAD

**Issue by Krukov** [Krukov/amocrm_api#28]
В связи с большими изменениями во взаимодействии с AmoCrm  и популярности этой платформы появились планы реанимировать библиотеку.
В планах 
- Реализовать авторизацию по Oauth2 (с api для хранения токенов)
- Сделать api более прозрачным  и простым
- Добавить недостающий функционал

**Comment by alewkinr** [comment]
@Krukov хочу и могу помочь, если сможешь поревьюить мои PR. Что думаешь?

**Comment by Krukov** [comment]
@alewkinr Да буду рад помощи.
 Правда я хотел сделать базовый (внутренний) интерфейс сам, но нужна будет помощь по добавлению api по конкретным сущностям amocrm  (сделки, пайплайны, контакты, etc).
Я сделаю отдельные задачи на реализацию этих обертк.

**Comment by alewkinr** [comment]
@Krukov 
круто, давай

Тогда либо в этой ишью напиши, либо я доступен в телеграм: @ramjet

**Comment by Krukov** [comment]
@alewkinr Новая версия в мастере, сори, за помощью не обратился. 
Сейчас много реализовано, всяких мелочей может не хватает, и очень не хватает юнитов,  было бы круто если они были. так что если есть желание то MR welcome! то это бы сильно помогло проекту.
