### ISSUE TITLE
Как добавить событие (Note) к сделке?

### ISSUE THREAD

**Issue by apenshin** [Krukov/amocrm_api#30]
Не могу разобраться  как добавить примечание к сделке?
lead = Lead(name='Имя')
lead.notes = ?

**Comment by Krukov** [comment]
В новой версии 
```python 
lead.notes(text="Сообщение").save()
```

**Comment by Krukov** [comment]
@apenshin  помогло?

**Comment by apenshin** [comment]
Спасибо.
Второй вариант сработал.
Так lead.notes.objects.create(text="Примечание") не получилось. Ошибка - нет атрибута text

**Comment by Krukov** [comment]
Спасибо
