### ISSUE TITLE
Метод добавления звонка

### ISSUE THREAD

**Issue by 2TQMdj** [Krukov/amocrm_api#34]
Подскажите, планируется добавление метода /api/v4/calls? Или возможно ли реализовать его вручную?

**Comment by Krukov** [comment]
Пока таких планов не было, но реализовать не сложно, могу добавить быстренько что то. Там же только создание?
Можете описать какой у вас флоу (юзер кейс)?

**Comment by 2TQMdj** [comment]
Да, только создание.
Сейчас реализовал вот таким образом:
data = [{
            "direction":direction,
            "duration": duration,
            "source": "someSource",
            "phone": phone,
            "created_by": userId,
            "created_at": createdAt,
            "link": link

        }]
        result = BaseInteraction().request("post", "calls", data)

**Comment by Krukov** [comment]
Да я думаю могу добавить более простые интерфейсы для создания звонков на недели
```python
from amocrm.v2 import Call, Contact

Call(phone=..., ...).save()

Contact.objects.get(id).save_call(...)
```

**Comment by Krukov** [comment]
Получилось не совсем так задумывалось - более по простому . см в readme
