### ISSUE TITLE
Lead.objects.all() возвращает 250 значений. Как получить все лиды из Амо?

### ISSUE THREAD

**Issue by dinodigital** [Krukov/amocrm_api#35]
Добрый день. Подскажите, пожалуйста, как получить всех лидов из Амо?

**Comment by Krukov** [comment]
Похоже на багу, протестирую фикс и залью в мастер

**Comment by Krukov** [comment]
Проверил у себя после фиксов получилось так - должно работать 2.3.0
 ```
 In [3]: len(list(Lead.objects.all()))
Out[3]: 8149
```

**Comment by dinodigital** [comment]
Работает, спасибо!
