### ISSUE TITLE
User.objects.all() возвращает пустой генератор

### ISSUE THREAD

**Issue by dinodigital** [Krukov/amocrm_api#40]
При вызове метода `User.objects.all()` возвращается генератор (`<generator object Manager.filter at 0x7f9c104aa270>`), но при прокрутке пустота:

```
users = User.objects.all()

for u in users:
    print(u)
```

При этом если запрашивать юзеров через `BaseInteraction().request("get", path="users")`, то всё приходит.

**Comment by Krukov** [comment]
Обсудили, пофиксили
