### ISSUE TITLE
Как создать новую задачу? 

### ISSUE THREAD

**Issue by ivkhokhlov** [Krukov/amocrm_api#42]
Привет, подскажите как создать задачу для лида? Не могу разобраться, в примерах о Task ничего не нашел

**Comment by ivkhokhlov** [comment]
разобрался
импорт через
`from amocrm.v2 import Task`
не работает, нужно использовать
`from amocrm.v2.entity.task import Task`
для добавления задачи к сделке заработал такой вариант
`Task.objects.create(entity_id='id сущности', entity_type='тип сущности, для лидов "leads"', text='комментарий к задаче",  complete_till="время в unix timestamp с преобразованием в int")))`

* без указания entity_type выдает ошибку, хотя это необязательный параметр
* для complete_till не подходит формат datetime, который по умолчанию используется в lead.created_at

**Comment by Krukov** [comment]
Привет, спасибо, поправлю замечания, пусть пока задача повесит

**Comment by JasurIsroilov** [comment]
Task.entity_id -> обязательное поле. Невозможно добавить задачу

**Comment by Krukov** [comment]
https://pypi.org/project/amocrm-api/2.5.0/
