### ISSUE TITLE
InvalidAudienceError: Invalid audience

### ISSUE THREAD

**Issue by likeblood** [Krukov/amocrm_api#43]
https://github.com/Krukov/amocrm_api/blob/d90b28815ecee6808bedfae21d2922f14e5b67a7/amocrm/v2/tokens.py#L161

При валидации access токена нужно явно передать audience. Ошибка выходит сразу же при любом запросе.

**Comment by Krukov** [comment]
Добрый, какая у вас версия pyjwt ?

**Comment by Krukov** [comment]
Подзависимости (pyjwt и requests)  не закреплены, но проверьте что pyjwt >= 2.0.0

https://pyjwt.readthedocs.io/en/stable/usage.html#reading-the-claimset-without-validation
