### ISSUE TITLE
Фильтр сделок

### ISSUE THREAD

**Issue by hawkkoff** [Krukov/amocrm_api#44]
Добрый день

Подскажите пожалуйста, как пользоваться Lead.objects.filter() ??? Как задавать параметры? Пытаюсь выбрать все лиды в статусе = " Успешно завершено"

**Comment by Krukov** [comment]
Добрый день.

Честно сам почти не тестировал - но должно быть как то так
```python
from amocrm.v2 import Lead
from amocrm.v2.filters import SingleFilter

Lead.objects.filter(filters=[SingleFilter("status")("Успешно завершено")])

#  если не сработает то можно попробовать по id стутуса (его можно найти в настройках или путем получения сделкт с таким статусом
STATUS_ID = 102

Lead.objects.filter(filters=[SingleFilter("status")(STATUS_ID)])
```

**Comment by Shmanov** [comment]
Добрый день. Подскажите пожалуйста, как отфильтровать одновременно сделки со статусом 102 и например 143?
