### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by Golova1111** [Krukov/amocrm_api#53]
Для корректной работы генерации файла с готовым мапингом требуется библиотека https://github.com/un33k/python-slugify или любая другая с подобным функционалом/сигнатурой, прошу обновить зависимости

**Comment by Krukov** [comment]
Спасибо, я умышлено не включал его в список зависимотей так как для основной работы библиотеки он она не нужна  и мне как потребителю этой либы тоже не хотелось бы что бы эта "мусорная" ) зависимость не шла вместе с библиотекой. 
Однако, я не прав и стоило бы упомянуть об этой неявной зависимости хотя бы в ридми

**Comment by Golova1111** [comment]
Спасибо и спасибо за действительно хороший враппер

**Comment by Krukov** [comment]
Спасибо большое! Рад если кому то он помог хотя-бы немного )
