### ISSUE TITLE
How to get messages from whatsapp integration?

### ISSUE THREAD

**Issue by kfcaio** [Krukov/amocrm_api#54]
Hi,

I'm looking for a way to retrieve messages from [whatsapp integration](https://www.amocrm.com/integrations/whatsapp/) . That integration is set on a phone I don't have access, so it'd be great if I could work around it.

I have access to leads and other entities mapped, but I'm clueless about how to interact with integrations and widgets, is it possible? If so, what is a viable way to do that? I'm open to contribute : )

My use case is quite simple: I don't have access to individual whatsapp notifications. In other words, I have to check each lead in order to know if he/she answers my message or dive into notifications (I'm not able to filter only my clients). I want to interact problematically with chat messages.

**Comment by Krukov** [comment]
Hi, 

I have never worked with integrations/widgets in AmoCRM, and it is look like a big deal to solve you issue.

I only have an idea, you can try to create webhook manually for chat messages ( https://www.amocrm.com/developers/content/digital_pipeline/dp-webhooks/ ) or by api  for `note_lead`,  `note_contact` or `update_lead` events https://www.amocrm.com/developers/content/api_v4/webhooks-2/#webhooks-available-actions (this library haven't wrapper for this entity)  and only than check a lead messages

**Comment by kfcaio** [comment]
Thank you, I'll take a look at your suggestions
