### ISSUE TITLE
ModuleNotFoundError: No module named 'amocrm.v2'; 'amocrm' is not a package

### ISSUE THREAD

**Issue by mexico76** [Krukov/amocrm_api#55]
Установил pip install amocrm_api
Создал простой файл. 

from amocrm.v2 import tokens, Contact

tokens.default_token_manager(
    client_id="xxx-xxx-xxxx-xxxx-xxxxxxx",
    client_secret="xxxx",
    subdomain="subdomain",
    redirect_url="https://xxxx/xx",
    storage=tokens.FileTokensStorage(),  # by default FileTokensStorage
)
tokens.default_token_manager.init(code="..very long code...", skip_error=True)
contacts = Contact.objects.all()
print(contacts)

И запуститл, в ответ ошибка 

root@67d3abe17a1b:/backend# python data/amocrm.py
Traceback (most recent call last):
  File "/backend/data/amocrm.py", line 1, in <module>
    from amocrm.v2 import tokens, Contact
  File "/backend/data/amocrm.py", line 1, in <module>
    from amocrm.v2 import tokens, Contact
ModuleNotFoundError: No module named 'amocrm.v2'; 'amocrm' is not a package

**Comment by Krukov** [comment]
Здравствуй,

А какой версии у тебя python?

**Comment by Krukov** [comment]
+ попробуй переименовать data/amocrm.py а то название файла пересекается с название пакета

**Comment by mexico76** [comment]
Да проблема решена [https://github.com/Krukov/amocrm_api/issues/55#issuecomment-959724777](url)
Подскажите такой вопрос, в этой библиотеке реализовано обновление access token-а?

**Comment by Krukov** [comment]
Да он сам в обновляется в случае если он заэкспарился и рефреш токен не просрочился

**Comment by Vinsick** [comment]
<generator object Manager.filter at 0x0000024331DA99A0>

Получаю в ответ, хелп
