### ISSUE TITLE
Как получить Дату закрытия Сделки?

### ISSUE THREAD

**Issue by nefella** [Krukov/amocrm_api#61]
Добрый день! 
Подскажите, пожалуйста, как можно получить Дату закрытия Сделки (это [одно из стандартных свойств](https://www.amocrm.ru/developers/content/crm_platform/leads-api) - closed_at)? 

Пробовала добавить её, как кастомное поле, но не сработало:
```
class Lead(_Lead):
    closing_date = custom_field.DateTimeCustomField("closed_at")
```

**Comment by Krukov** [comment]
Добрый день
Странно почему-то пропустили это поле при реализации (

Думаю в понедельнику добавлю это поле, а пока могу предложить как то так сделать 

```python
from amocrm.v2.fields import _DateTimeField

class Lead(_Lead):
    closed_at = fields._DateTimeField("closed_at")

```

**Comment by Krukov** [comment]
Добавил это поле в новой вервии 

https://pypi.org/project/amocrm-api/2.4.0/

**Comment by nefella** [comment]
Спасибо большое! И в целом спасибо за библиотеку!! Использую её для настройки сквозной аналитики в небольшом проекте)

**Comment by Krukov** [comment]
спасибо. отлично что она кому-то помогает )
