### ISSUE TITLE
Как добавлять и просматривать товары?

### ISSUE THREAD

**Issue by radioset** [Krukov/amocrm_api#62]
Не нашел как работать со списком "products".
Подскажите.

**Comment by Krukov** [comment]
Здравствуй.  Эта часть не был реализована, так как пока вообще не ясно как с этим правильно работать

**Comment by radioset** [comment]
Планирую бота на aiogram интегрировать с amoCRM. Подгружать товары в бота из CRM.
И при покупке создавать сделку в которой данный товар указан.
Пока конечно есть выход хранить товары в PostgreSQL и управлять базой через Django.
А заказы передавать в amoCRM.
Но хотелось бы из одной системы все делать.

**Comment by Krukov** [comment]
Да в Амосрм если даже можно сделать получение списка товаров то как ее привязать к сделке не ясно - если только через кастомные поля указывать что за товар. 

Могу попробовать в слепую запилить апи для получения списка товаров, но ты используешь aiogram - а он асинхронный, а этот враппер синхронный так что надо его оборачивать в ThreadPoolExecuter
