### ISSUE TITLE
Pipeline

### ISSUE THREAD

**Issue by Colcefer** [Krukov/amocrm_api#63]
Не пойму как получить pipeline сделки
`<generator object Manager.filter at 0x000001BA10750F20>`
Как распаковать этот ответ?

`leadget1 = Pipeline.objects.filter(pipeline_id=45884164)`
вот так собственно я ищу просто pipeline. пробовал с разных сторон заходить. Уже два дня бьюсь. Мб потому что не особо опытен

Короче, я просто хочу получить все сделки в определенном pipeline =(

**Comment by Krukov** [comment]
```python
leadget1 = list(Pipeline.objects.filter(pipeline_id=45884164))
```

**Comment by Colcefer** [comment]
> ```python
> leadget1 = list(Pipeline.objects.filter(pipeline_id=45884164))
> ```

Спасибо большое!
Хотел бы предложить помощь в редактировании документации и прочее. Нравится этот проект. Но я новичок, и ранее таким не занимался.

**Comment by Colcefer** [comment]
> ```python
> leadget1 = list(Pipeline.objects.filter(pipeline_id=45884164))
> ```

Спасибо за совет по обработке генеработа, он был тупой однако =(

`f = list(Lead.objects.filter(filters=(filters.RangeFilter("created_at")(value_from="f", value_to="t"),)))`
это использование Range фильтра, но мне необходим фильтр по статусам, не могли бы вы мне помочь?

**Comment by Colcefer** [comment]
> ```python
> leadget1 = list(Pipeline.objects.filter(pipeline_id=45884164))
> ```

`f = list(Lead.objects.filter(filters=(filters.EventsFiltersByPipelineAndStatus("status_id")(pipline_id="5113246", status_id="46175128"),)))`

Почему это возвращает мне все сделки, а не нужного мне статуса? Не могу понять

**Comment by Colcefer** [comment]
`f2 = list(Lead.objects.filter(filters=(filters.EventsFiltersByPipelineAndStatus("statuses")(pipline_id="5113246", status_id="46175128"),)))`
Доброго вечера, извините за неудобства. Почему не работает этот фильтр по статусу? Он возвращает все сделки. Не ругаясь на ошибки

**Comment by Colcefer** [comment]
> `f2 = list(Lead.objects.filter(filters=(filters.EventsFiltersByPipelineAndStatus("statuses")(pipline_id="5113246", status_id="46175128"),)))` Доброго вечера, извините за неудобства. Почему не работает этот фильтр по статусу? Он возвращает все сделки. Не ругаясь на ошибки

Пришлось создать новый класс в filters 
```
class FiltersByPipelineAndStatus(Filter):
    def __call__(self, pipline_id, status_id):
        self._pipline_id = pipline_id
        self._status_id = status_id
        return self

    def _as_params(self):
        return {
            "filter[{}][0][pipeline_id]".format(self._name): self._pipline_id,
            "filter[{}][0][status_id]".format(self._name): self._status_id,
        }
```
Может быть они немного конструкцию запроса поменяли...

**Comment by Krukov** [comment]
Хм  - ну вообще EventsFiltersByPipelineAndStatus относится только к эвентам - поэтому он вам не подойдет
 К сожаление сам этот функционал в либе слабо оттестирован
 
 
 Да, похожу ваш вариант верный судя по доке https://www.amocrm.ru/developers/content/crm_platform/filters-api#%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80-%D0%BF%D0%BE-%D1%81%D1%82%D0%B0%D1%82%D1%83%D1%81%D0%B0%D0%BC 

Было бы хорошо его добавить

**Comment by Colcefer** [comment]
> Хм - ну вообще EventsFiltersByPipelineAndStatus относится только к эвентам - поэтому он вам не подойдет К сожаление сам этот функционал в либе слабо оттестирован
> 
> Да, похожу ваш вариант верный судя по доке https://www.amocrm.ru/developers/content/crm_platform/filters-api#%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80-%D0%BF%D0%BE-%D1%81%D1%82%D0%B0%D1%82%D1%83%D1%81%D0%B0%D0%BC
> 
> Было бы хорошо его добавить

Я могу помочь с этим если нужно. Я правда не особо опытен, но это был бы хороший пункт в резюме, если вы меня где нибудь внизу в титрах укажете)

**Comment by Krukov** [comment]
Без проблем, будет классно и мне и тебе полезно

**Comment by sadyrov12349** [comment]
Добрый день! спасибо за ваш труд и вклад, есть решения этого изменения
