### ISSUE TITLE
Как обойти ошибку amocrm.v2.exceptions.AmoApiException: Connection aborted? 

### ISSUE THREAD

**Issue by Shelnadya** [Krukov/amocrm_api#67]
Здравствуйте! Делаю выгрузку из events log, используя Event from amocrm.v2 – [код здесь](https://www.online-python.com/HbAkrysEU7). Иногда выгрузка отваливается с ошибкой # Sometimes Connection aborted. amocrm.v2.exceptions.AmoApiException: Connection aborted. Я пробовала варьирование продолжительности задержки и размеров батчей – ничего не помогает. Как обойти описанную выше проблему?

**Comment by Krukov** [comment]
Здравствуйте проблема еще актуальна?  Я не вижу других способов кроме как обрабатывать ошибку и пробовать снова. По идее езе можно пропатчить сессию requests что бы на уровне библиотеки делались ретраи

**Comment by Shelnadya** [comment]
Здравствуйте! Проблема еще актуальна 
> напишите я объясню как сделать
это очень поможет!

**Comment by Shelnadya** [comment]
спасибо!

**Comment by vprsnc** [comment]
Помогает 

> Я тогда предлагаю где-то на верхнем уровне ( возможно в блоке импортов) поставить вот такой блок
> 
> ```python
> from requests.adapters import HTTPAdapter
> from amocrm.v2.interaction import _session
> _session.mount("https://", HTTPAdapter(max_retries=5))
> ```
> 
> Мы тут в дефолтную сессию requests которая используется для запросов стандартными механизмами requests добавляем ретраи. Надеюсь поможет

Помогает эта штука, спасибо!
