### ISSUE TITLE
Создание сделки в статусе неразобранное

### ISSUE THREAD

**Issue by lost4815162342** [Krukov/amocrm_api#69]
Пытаюсь создать неразобранную сделку:

`Lead.objects.create(name='Нераз.Сделка', status_id=48692119, pipeline_id=5503552)`

Получаю ошибку:

> amocrm.v2.exceptions.ValidationError: {'validation-errors': [{'request_id': '0', 'errors': [{'code': 'NotSupportedChoice', 'path': 'status_id', 'detail': 'The value you selected is not a valid choice.'}]}], 'title': 'Bad Request', 'type': 'https://httpstatus.es/400', 'status': 400, 'detail': 'Request validation failed'}

ID шники статуса и  pipeline перепроверял:

> Status(color = #c1c1c1, id = 48692119, is_editable = False, name = Неразобранное, sort = 10, type = 1)

Каков правильный путь для создания неразобранной сделки?

**Comment by Krukov** [comment]
Привет - если честно не сталкивался с такой проблемой. А получаеться в другом статусе создавать?
Вообще я посмотрел я обычно при создании только статус указывал ( айдишник)

```python
INITIAL_STATUS = "Новая заявка"
PIPELINE_ID = 2314214

lead = Lead(
        ...
        status=_get_initial_status(),
        ...
 )

@lru_cache(None)
def _get_pipeline():
    return Pipeline.objects.get(object_id=PIPELINE_ID)


@lru_cache(None)
def _get_initial_status():
    return Status.get_for(_get_pipeline()).get(query=INITIAL_STATUS)
```

**Comment by lost4815162342** [comment]
В любом другом статусе создавать получается.
Выяснилось, что неразобранные это особый вид сделок, для них отдельный сервис 'leads/unsorted' и своя логика построения запроса
Если переопределить:
`LeadsInteraction.path = "leads/unsorted"`
и переопределеить разбор ответа то ОК. Но это конечно костылестроение.
Буду надеяться, дойдут руки сделать адекватно и отправить реквест сюда.

**Comment by Krukov** [comment]
спасибо за инфу. Обожаю АПИ АМОСРМ ))

**Comment by ersnick** [comment]
Как по итогу должно выглядеть создание неразобранной сделки? можно пример, пожалуйста?)
