### ISSUE TITLE
FiltersByPipelineAndStatus

### ISSUE THREAD

**Issue by sadyrov12349** [Krukov/amocrm_api#70]
подскажите пожалуйста как могу использовать FiltersByPipelineAndStatus фильтр что то не могу понять (я новичек) спасибо заранее

**Comment by Krukov** [comment]
Привет

 сори по-моему пока FiltersByPipelineAndStatus не зарелижен - то есть можно использовать только в мастере

**Comment by sadyrov12349** [comment]
спасибо
