### ISSUE TITLE
List index out of range при попытке забрать Event

### ISSUE THREAD

**Issue by vprsnc** [Krukov/amocrm_api#72]
Привет @Krukov!
У меня возникает вышеозначенная ошибка, когда я пытаюсь забрать Event из амо

`events = list(Event.objects.filter(filters=[filters.DateRangeFilter("created_at")(now-timedelta(days=1), now)]))`
`events`

Причем та же ошибка возникает, если просто делать, хотя раньше возвращало просто последнее событие:

`Event.objects.get()`

Мб бага какая?

**Comment by vprsnc** [comment]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/IPython/core/formatters.py:707, in PlainTextFormatter.__call__(self, obj)
    700 stream = StringIO()
    701 printer = pretty.RepresentationPrinter(stream, self.verbose,
    702     self.max_width, self.newline,
    703     max_seq_length=self.max_seq_length,
    704     singleton_pprinters=self.singleton_printers,
    705     type_pprinters=self.type_printers,
    706     deferred_pprinters=self.deferred_printers)
--> 707 printer.pretty(obj)
    708 printer.flush()
    709 return stream.getvalue()

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/IPython/lib/pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/IPython/lib/pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/amocrm/v2/model.py:40, in Model.__repr__(self)
     39 def __repr__(self):
---> 40     fields = [
     41         "{} = {}".format(field.name, getattr(self, attr))
     42         for attr, field in inspect.getmembers(self.__class__)
     43         if isinstance(field, _FIELDS_FOR_REPR)
     44     ]
     45     return "{self.__class__.__name__}({fields})".format(self=self, fields=", ".join(fields))

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/amocrm/v2/model.py:41, in <listcomp>(.0)
     39 def __repr__(self):
     40     fields = [
---> 41         "{} = {}".format(field.name, getattr(self, attr))
     42         for attr, field in inspect.getmembers(self.__class__)
     43         if isinstance(field, _FIELDS_FOR_REPR)
     44     ]
     45     return "{self.__class__.__name__}({fields})".format(self=self, fields=", ".join(fields))

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/amocrm/v2/fields.py:33, in _BaseField.__get__(self, instance, _)
     31 if data is None and not self._blank:
     32     raise exceptions.NoDataException(str(self))
---> 33 return self.on_get_instance(instance, data)

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/amocrm/v2/entity/events.py:93, in _EventValueField.on_get_instance(self, instance, value)
     91     return value[0]["transaction"]["id"]
     92 if instance.type in EVENT_TYPES_WITH_NOTE:
---> 93     return value[0]["note"]["id"]
     94 if instance.type == EVENT_TYPE_NPS_RATE_ADDED:
     95     return value[0]["nps"]["rate"]

IndexError: list index out of range

**Comment by vprsnc** [comment]
При этом то же самое возникает, если забирать более ранние события:
`events = Event.objects.filter(filters=[filters.DateRangeFilter("created_at")(now-timedelta(days=2), now-timedelta(days=1))])`

**Comment by Krukov** [comment]
Прости, мало времени что бы посмотреть по подробнее,  но вообще если раньше работало а теперь нет то амосрм могли изменить чуть свою апи - так уже было. Но может и бага на стороне библиотеки - попробую  попозже.

**Comment by vprsnc** [comment]
В общем, если фильтровать по какому-то определённому типу, то все нормально работает

Вернее работало, создал новую issue

**Comment by Krukov** [comment]
https://pypi.org/project/amocrm-api/2.5.0/
