### ISSUE TITLE
Удаётся забрать только первые 50 событий из Event

### ISSUE THREAD

**Issue by vprsnc** [Krukov/amocrm_api#76]
Раньше все хорошо работало, но теперь при любой попытке забрать Event любым способом, выдаётся только 50
Пробовал так:
`events = list(Event.objects.filter(
    filters=[
        filters.DateRangeFilter("created_at")(now-timedelta(days=7), now),
        filters.SingleFilter("type")("lead_status_changed")
    ]
))`
и так:
`events = list(Event.objects.all())`

**Comment by AndrejGorodnij** [comment]
Форкнул и добавил PR с фиксом, ждите обновления, если автор одобрит.

**Comment by Krukov** [comment]
Конечно одобрим

**Comment by vprsnc** [comment]
> Форкнул и добавил PR с фиксом, ждите обновления, если автор одобрит.

Спасибо вам большое, добрый человек!

**Comment by vprsnc** [comment]
Привет @Krukov ! Как там дела с апдейтом? У меня всё ещё ивенты по 50 забираются...

**Comment by Krukov** [comment]
https://pypi.org/project/amocrm-api/2.5.0/

**Comment by vprsnc** [comment]
В общем, обновился до 2.5.0, все ещё 50 событий забирается

**Comment by Krukov** [comment]
Странно - у меня все хорошо. Проверьте тогда мануально (curl, postman, etc )- может проблема на стороне амосрм

**Comment by Shelnadya** [comment]
Привет @Krukov! Тоже со вчерашнего числа выдается только 50 событий, хотя раньше все работало отлично 
Даже Event.objects.all() выдает только 50 событий

**Comment by Krukov** [comment]
мне все больше кажется что это какая-то дич на стороне amocrm

**Comment by karlson71** [comment]
Привет, столкнулся с такой же проблемой. Нужно вытаскивать все события, но получается только 50 элементов, подскажи может ты знаешь как вытащить ивенты по-другому? хелп плиз

**Comment by Krukov** [comment]
Привет. Я других способов не знаю - все жду что кто то найдет причину )) или предложит хотябы фикс

**Comment by Krukov** [comment]
спасибо @vbn22 за фикс
