### ISSUE TITLE
Невозможно создать Task

### ISSUE THREAD

**Issue by JasurIsroilov** [Krukov/amocrm_api#79]
Привет. Спасибо за библиотеку, она очень проста в использовании. Но, задачу не создается, так как Task.entity_id является обязательным полем. Атрибута entity_id нет в классе

**Comment by AndrejGorodnij** [comment]
Entyti_id - это id родительской сущности, например сделки, для которой таска создается.

**Comment by Krukov** [comment]
Да нужно поправить - МР очень приветсвуется. Мне по сути не на чем даже тестить сейчас

**Comment by Krukov** [comment]
https://pypi.org/project/amocrm-api/2.5.0/
