### ISSUE TITLE
Как создать заявку одним запросом?

### ISSUE THREAD

**Issue by Colcefer** [Krukov/amocrm_api#80]
![image](https://user-images.githubusercontent.com/10243433/185758297-0be09264-5ba7-4431-8306-e71d56ee27eb.png)
Не пойму, как можно создать заявку сразу со всеми полями?

**Comment by AndrejGorodnij** [comment]
Поместить все параметры внутрь create() ?

**Comment by Colcefer** [comment]
> Поместить все параметры внутрь create() ?

Со стандартными полями работает спасибо, а с кастомными как быть?

**Comment by Colcefer** [comment]
Разобрался, через "data={json}"
