### ISSUE TITLE
Усовершенствование интеграции

### ISSUE THREAD

**Issue by JasurIsroilov** [Krukov/amocrm_api#83]
Добрый вечер! Получается я самый активный фанат библиотеки)
Можно ли добавить возможность создания сразу несколько интеграций? Я понял, что библиотека работает только с одним объектом default_token_manager класса Token_Manager

**Comment by Krukov** [comment]
Привет. ну вообще специально есть объект Token_Manager что бы работать можно было с несколькими  интеграциями если так хочется - но конечно сама работа будет немного по другому выглядить 

По идеи можно вот так
```python
from amocrm.v2.manager import Manager
from amocrm.v2.entity.lead import LeadsInteraction, Lead
from amocrm.v2.tokens import TokenManager, FileTokensStorage

my_token_manager = TokenManager()
my_token_manager(
    client_secret="settings.AMOCRM_CLIENT_SECRET",
    storage=FileTokensStorage(directory_path="."),
)

interaction = LeadsInteraction(token_manager=my_token_manager)
Leads = Manager(interaction, Lead)
Leads.get(object_id=24244)
Leads.all()
Leads.create(...)
```
