### ISSUE TITLE
Не удаётся привязать основной контакт к сделке 

### ISSUE THREAD

**Issue by radiosterne** [Krukov/amocrm_api#86]
Код:

```
new_lead.contacts.append(contact, True)
```
, в котором `new_lead` — это `Lead`, а `contact` — это `Contact`,
выбрасывает исключение:

```
{'validation-errors': [{'request_id': '0', 'errors': [{'code': 'FieldNotExpected', 'path': 'metadata.main', 'detail': 'This field was not expected.'}]}], 'title': 'Bad Request', 'type': 'https://httpstatus.es/400', 'status': 400, 'detail': 'Request validation failed'}
```

Оно связано с тем, что поле `main` передаётся в запросе к Амо в ключе с именем `main`, хотя по документации это `is_main` (https://www.amocrm.ru/developers/content/crm_platform/leads-api#leads-add).

Поправлено в пулл-реквесте #85

**Comment by Krukov** [comment]
Спасибо, замержил но пока не выпускал новую версию
