### ISSUE TITLE
Как применять дополнительные Get параметры?

### ISSUE THREAD

**Issue by zhuravkov** [Krukov/amocrm_api#87]
Подскажите, как применять дополнительные Get параметры, например совершить такой запрос      
res = requests.get(f'https://{account}.amocrm.ru/api/v4/leads', params={'with':'contacts'}, headers=api_call_headers)?

**Comment by Krukov** [comment]
Привет - у либы другая концепция. Если хочется самому управлять параметрами запроса то лучше и напрямую использовать requests
