### ISSUE TITLE
Не обновляется кастомное поле типа bool

### ISSUE THREAD

**Issue by Ilya240980** [Krukov/amocrm_api#88]
Имеется кастомное поле в сделке

notify = custom_field.CheckboxCustomField("Notify", field_id=10801xx)

def flag_notify(id,flag):
    logger.info("Добавляю флаг отправки в %s",flag)
    lead=Lead.objects.get(object_id=int(id))
    lead.notify=flag
    lead.save()

flag_notify(2714xx,True) флаг устанавливается 

flag_notify(2714xx,None) флаг не выключается, ошибок нет.

что я делаю не так?

**Comment by Krukov** [comment]
а не пробовал 
```
flag_notify(2714xx, False) 
```
?
