### ISSUE TITLE
Как правильно получить элементы сущности по по фильтру? 

### ISSUE THREAD

**Issue by ilyailyushko** [Krukov/amocrm_api#92]
Привет, не получается получить лиды на определенном статусе, в РИДми есть пример:

```
<Entity>.objects.filter(**kwargs)  # получение списка сущностей с фильтром
```

Пытаюсь получить все лиды в статусе новый, но выдает ошибку =( 

Какое бы значение я не передавал в фильтр, ругается что такого поля нет
```
leads = Lead.objects.filter(status_id=52689682)
# GenericInteraction.get_all() got an unexpected keyword argument 'status_id'

leads = Lead.objects.filter(status_id=52689682)
# GenericInteraction.get_all() got an unexpected keyword argument 'status'
```
Подскажите, что я не так делаю?

**Comment by Luckyenough64** [comment]
Подпишусь, какие аргументы указывать нужно? из оф. документации?

**Comment by Krukov** [comment]
Да простите за долгий ответ - вообщем посмотрите на пример вот тут 

https://github.com/Krukov/amocrm_api/issues/70#issuecomment-1174234648

Там нужно обязательно и статус и айди воронки

**Comment by Krukov** [comment]
если не по статусу то вот ту есть примеры как использовать фильтры по датам 
https://github.com/Krukov/amocrm_api/issues/71

**Comment by KozyrevIvan** [comment]
Я сейчас сделал  доработку для формирования фильтра на основе поля.
```python
Lead.objects.filter(filter=(Lead.phone.filter_single("79*********")), order=Lead.created_at.order_asc())
```
Такая конструкция более удобная.

**Comment by Krukov** [comment]
@KozyrevIvan  если там только под питон 3.11 то наверное не очень хорошо для либы. А вообще интересно  можно кинуть пр а там уже посмотрим ))
