### ISSUE TITLE
Получение информации о кастомных полях для каждой сделки

### ISSUE THREAD

**Issue by sinevivan** [Krukov/amocrm_api#93]
Подскажите пожалуйста, как я могу получить значения кастомных полей в сделке? 

Получил все сделки следующим образом
```
leads = list(Lead.objects.filter(filters=[filters.DateRangeFilter("created_at")\
                                  (now-timedelta(days=5), now)]))

```

далее через dir перебрал все методы, нигде информации этой нет

нашел следующий класс(?) _get_embedded_fields, но что с ним делать, не понятно

если пременить к сделке, то получается следующее

```
leads[1]._get_embedded_fields

out:
<bound method Model._get_embedded_fields of <class 'amocrm.v2.entity.lead.Lead'>>
```

Прочитал ответы, на счет создания и записи полей
Но про получение не нашел информации
Уровня питона не хватает, чтобы разобраться в документации

Надеюсь поможете!(

**Comment by Krukov** [comment]
Вам нужно создать маппинг для полей  (в амосрм полюбому у них есть какие-то названия ) 
Вы создаете свой класс сделки  где их описываете  ( название и тип) ( это не про создание полей - сама либа их не создает )
```python
from amocrm.v2 import Lead as _Lead, custom_field

class Lead(_Lead):
    utm = custom_field.UrlCustomField("UTM метка")
    delivery_type = custom_field.SelectCustomField("Способ доставки")
    my_field = custom_field.TextCustomField("Мое поле")
```
и тогда вы сможете получить его/их значение 
```python
leads[1].my_field 
...
```
